- distribution/scripts/jmeter/run-performance-tests.sh
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Enable SAML SSO Test Case

- distribution/scripts/jmeter/saml/SAML2_SSO_Redirect_Binding.jmx
This PR contains changes like: 
1. Increased ramp-up time
2. add post-processer to start next loop in the case of failure
> improve saml sso script

- README.md
- cloudformation/start_performance_single.sh
- distribution/scripts/jmeter/run-performance-tests.sh
- distribution/scripts/jmeter/templates/summary.md
- distribution/scripts/setup/setup-bastion.sh
- distribution/scripts/setup/single-node-setup/isserver_edit.sh
- distribution/scripts/setup/single-node-setup/setup_is.sh
- pom.xml
> Some improvements were done to the script files.
> Improvements to single-node setup

- cloudformation/singlenode/single-node.yaml
- cloudformation/start_performance_single.sh
- distribution/scripts/jmeter/run-performance-tests.sh
contain logic to parameterize DB instance type
copies the http_access_log to the results
> parameterize DB instance type

- distribution/scripts/jmeter/run-performance-tests.sh
This PR
1.  stop IS from transferring http access log
2. add timestamp in local time zone
> Remove transfer http access log

- cloudformation/singlenode/single-node.yaml
- add RDS storage size and IOPS configuration
- change default storage type from gp2 to io1
> add storage configuration to RDS

- cloudformation/singlenode/single-node.yaml
- install java from JDK in cfn
> Install Java from JDK setup

- cloudformation/start_performance_single.sh
- distribution/scripts/jmeter/perf-test-is.sh
- distribution/scripts/jmeter/run-performance-tests.sh
- Few important updates to the docker setup.
- Comment out SCIM tests
> Single node performance docker

- cloudformation/start_performance_single.sh
> avoid confusion between VM stack name and Docker stack name
> Changed Docker stack name
> stack name refactored for docker

- benchmarks/single-node-4-core-2G-heap-5.9.0-2019-10-03.md
Add product version 5.9.0 performance results.
> Add product version 5.9.0 performance results

- benchmarks/README.md
$subject and corrected 5.8.0 server version names
> Update Readme.md to add 5.9.0 perf results

- benchmarks/5.9.0-single-node-2-core.md
Add 5.9.0 single node two core test results
> Add 5.9.0 single node two core test results

- benchmarks/5.7.0_single-node_4-core.md
- benchmarks/README.md
Include test result file of product version 5.7.0, single node 4 core
> Add 5.7.0_single-node_4-core test results

- benchmarks/5.6.0_single-node_2-core.md
- benchmarks/5.7.0_single-node_2-core.md
- benchmarks/README.md
Add performance test results, 5.6.0_single-node_2-core  and 5.7.0_single-node_2-core
> Add performance test results

- benchmarks/5.6.0_single-node_4-core.md
- benchmarks/5.8.0_single-node_2-core.md
- benchmarks/5.8.0_single-node_4-core.md
- benchmarks/README.md
Add following performance test result and update Readme file
- 5.6.0_single-node_4-core.md
- 5.8.0_single-node_2-core.md
- 5.8.0_single-node_4-core.md
> Add 5,8.0 and 5.6.0 performance test results

- single-node/single-node.yaml
- two-node-cluster/2-node-cluster.yml
Update apt install queries to fix lock-frontend issue. [1]
[1] https://github.com/wso2/performance-is/issues/57
> Update apt install queries

- single-node/single-node.yaml
- two-node-cluster/2-node-cluster.yml
backporting [1]
[1] https://github.com/wso2/performance-is/pull/58
> Update apt queries

- common/jmeter/perf-test-is.sh
- common/jmeter/populate-data.sh
- single-node/start-performance.sh
- Added a new parameter that can be used to separately execute the scripts in four different steps as,
1 - stack creation only
2 - stack configuration only
3 - data population only
4 - test execution-only
**_Need to add readme updates before merging._**
> Add execution mode parameter

- single-node/setup/resources/deployment.toml
- two-node-cluster/setup/resources/deployment.toml
Add comment lines to toml files
> update the toml files

- README.md
- common/jmeter/templates/summary.md
- common/summary/summary-modifier.py
- single-node/bin.xml
- single-node/start-performance.sh
- two-node-cluster/start-performance.sh
This PR will lead to generating a separate result table for each test scenario of the performance test.
This will add a new python script named as summary-modifier.py to generate a summary.csv file with only required column names.
Further, summary.md template will also be modified by this PR to provide the required modification for the result table.
> Generate a separate result table for each scenario of the performance test

- single-node/start-performance.sh
- two-node-cluster/start-performance.sh
> Remove AWS key and secret from start scripts - 5.9.0

- single-node/start-performance.sh
- two-node-cluster/start-performance.sh
> Remove AWS key and secret from start scripts - 5.8.0

- single-node/start-performance.sh
- two-node-cluster/start-performance.sh
Refers: https://github.com/wso2/performance-is/issues/73
> Remove AWS key and secret from start scripts - master

- README.md
- common/jmeter/templates/summary.md
- common/summary/summary-modifier.py
- single-node/bin.xml
- single-node/start-performance.sh
- two-node-cluster/start-performance.sh
Refers: https://github.com/wso2/performance-is/issues/77
> Backport #70 to IS 5.8.0

- README.md
- common/jmeter/templates/summary.md
- common/summary/summary-modifier.py
- single-node/bin.xml
- single-node/start-performance.sh
- two-node-cluster/start-performance.sh
Refers: https://github.com/wso2/performance-is/issues/77
> Backport #70 to IS 5.9.0

- common/jmeter/oauth/OAuth_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oauth/OAuth_Password_Grant.jmx
- common/jmeter/oauth/OAuth_Password_Grant_Refresh_Token.jmx
- common/jmeter/oauth/OAuth_Password_Grant_Token_Introspection.jmx
- common/jmeter/oauth/OAuth_Password_Grant_Token_Revocation.jmx
- common/jmeter/oidc/OIDC_AuthCode_Request_Path_Authenticator_WithConsent.jmx
- common/jmeter/oidc/OIDC_Password_Grant.jmx
- Remove new lines added in response assertions.
- Rearrange few assertions as appropriate
Refers https://github.com/wso2/performance-is/issues/83
> Fix response assertion issue

- common/jmeter/oauth/OAuth_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oauth/OAuth_Password_Grant.jmx
- common/jmeter/oauth/OAuth_Password_Grant_Refresh_Token.jmx
- common/jmeter/oauth/OAuth_Password_Grant_Token_Introspection.jmx
- common/jmeter/oauth/OAuth_Password_Grant_Token_Revocation.jmx
- common/jmeter/oidc/OIDC_AuthCode_Request_Path_Authenticator_WithConsent.jmx
- common/jmeter/oidc/OIDC_Password_Grant.jmx
- Remove new lines added in response assertions.
- Rearrange few assertions as appropriate
Refers #83
> Backport #82 to IS 5.9.0

- common/jmeter/oauth/OAuth_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oauth/OAuth_Password_Grant.jmx
- common/jmeter/oauth/OAuth_Password_Grant_Refresh_Token.jmx
- common/jmeter/oauth/OAuth_Password_Grant_Token_Introspection.jmx
- common/jmeter/oauth/OAuth_Password_Grant_Token_Revocation.jmx
- common/jmeter/oidc/OIDC_AuthCode_Request_Path_Authenticator_WithConsent.jmx
- common/jmeter/oidc/OIDC_Password_Grant.jmx
Purpose
Remove new lines added in response assertions.
Rearrange few assertions as appropriate
Refers #83
> Backport #82 to IS 5.8.0

- single-node/run-performance-tests.sh
- two-node-cluster/run-performance-tests.sh
Remove invalid test from the script.The feature not available at the product version 5.10
> Remove invalid test from the script.

- two-node-cluster/bin.xml
> Fix the error when summarizing performance scripts
`./start-performance.sh: line 426: ./summary/summary-modifier.py: No such file or directory`
> Add md summary creation files to summary folder

- benchmarks/5.10.0/WUM/1600099543376/5.10.0_single-node_4-core.csv
- benchmarks/5.10.0/WUM/1600099543376/5.10.0_single-node_4-core.md
- benchmarks/5.10.0/WUM/1600099543376/5.10.0_two-nodes_4-core.csv
- benchmarks/5.10.0/WUM/1600099543376/5.10.0_two-nodes_4-core.md
- benchmarks/README.md
> Fix https://github.com/wso2/product-is/issues/8976
> Add 5.10 WUM Performance Numbers to benchmarks

- benchmarks/5.10.0/WUM/1600099543376/5.10.0_single-node_2-core.csv
- benchmarks/5.10.0/WUM/1600099543376/5.10.0_single-node_2-core.md
- benchmarks/5.10.0/WUM/1600099543376/5.10.0_two-nodes_2-core.csv
- benchmarks/5.10.0/WUM/1600099543376/5.10.0_two-nodes_2-core.md
- benchmarks/README.md
> Add 5.10 WUM 2 Core (single node, 2 nodes) Performance Results
> Add 5.10 WUM 2 Core Performance Results

- benchmarks/5.10.0/5.10.0_two-nodes_4-core.csv
- benchmarks/5.10.0/5.10.0_two-nodes_4-core.md
- benchmarks/README.md
> Add 5.10 GA two node 4 core results
> Add 5.10 GA two node 4 core results

- common/jmeter/setup/TestData_Add_Tenant_OAuth_Apps.jmx
- common/jmeter/setup/TestData_Add_Tenant_SAML_Apps.jmx
- common/jmeter/setup/TestData_Add_Tenants.jmx
> Use Rest API's for tenant wise SAML and OAuth Application Creation using Jmeter
Partially Fixes the issue: https://github.com/wso2-enterprise/asgardeo-product/issues/926
> Use Rest API's for tenant wise SAML and OAuth Application Creation using Jmeter

- common/is/clean-database-mssql.sql
- common/is/clean-database.sql
- common/jmeter/oidc/OIDC_Password_Grant.jmx
- common/jmeter/perf-test-pre-provisioned.sh
- common/jmeter/setup/TestData_Add_Tenant_OAuth_Apps.jmx
- common/jmeter/setup/TestData_Add_Tenant_SAML_Apps.jmx
- common/jmeter/setup/TestData_SCIM2_Add_Tenant_Users.jmx
- pom.xml
- pre-provisioned/README.md
- pre-provisioned/bastion-cft.yml
- pre-provisioned/bin.xml
- pre-provisioned/pom.xml
- pre-provisioned/run-performance-tests.sh
- pre-provisioned/setup/setup-bastion.sh
- pre-provisioned/setup/setup-jmeter-client-is.sh
- pre-provisioned/start-performance.sh
Fix: 
https://github.com/wso2-enterprise/asgardeo-product/issues/926
> Add Core support For tenant wise performance testing in pre provisioned enviroment

- common/jmeter/oauth/OAuth_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oauth/OAuth_Client_Credentials_Grant.jmx
- common/jmeter/oauth/OAuth_Implicit_Redirect_WithConsent.jmx
- common/jmeter/oauth/OAuth_Password_Grant.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oidc/OIDC_AuthCode_Request_Path_Authenticator_WithConsent.jmx
- common/jmeter/oidc/OIDC_Implicit_Redirect_WithConsent.jmx
- common/jmeter/oidc/OIDC_Password_Grant.jmx
- common/jmeter/saml/SAML2_SSO_Redirect_Binding.jmx
- common/jmeter/setup/TestData_Add_Tenant_OAuth_Apps.jmx
- common/jmeter/setup/TestData_Add_Tenant_SAML_Apps.jmx
> Support Consent in Jmeter Scripts
Fix: https://github.com/wso2-enterprise/asgardeo-product/issues/926
> Support Consent in Jmeter Scripts

- common/jmeter/oauth/OAuth_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oauth/OAuth_Implicit_Redirect_WithConsent.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oidc/OIDC_AuthCode_Request_Path_Authenticator_WithConsent.jmx
- common/jmeter/oidc/OIDC_Implicit_Redirect_WithConsent.jmx
- common/jmeter/perf-test-pre-provisioned.sh
- common/jmeter/setup/TestData_Add_Tenant_SAML_Apps.jmx
- pre-provisioned/run-performance-tests.sh
> Fix tenant endpoint issue in jmeter scripts
> Fix tenant endpoint issue in jmeter scripts

- single-node/run-performance-tests.sh
- two-node-cluster/run-performance-tests.sh
> Add identity DB as the selected database
> Add identity DB as the selected database

- pre-provisioned/start-performance.sh
> Remove echo command since it reveals passwords
> Remove echo command since it reveals passwords

- common/jmeter/authenticate/Authenticate_Super_Tenant_User.jmx
- common/jmeter/perf-test-is.sh
- common/jmeter/perf-test-pre-provisioned.sh
- common/jmeter/setup/TestData_Add_OAuth_Apps.jmx
- common/jmeter/setup/TestData_Add_SAML_Apps.jmx
- common/jmeter/setup/TestData_Add_Tenant_OAuth_Apps.jmx
- common/jmeter/setup/TestData_Add_Tenant_SAML_Apps.jmx
- common/jmeter/setup/TestData_Add_Tenants.jmx
- common/jmeter/setup/TestData_SCIM2_Add_Tenant_Users.jmx
- common/jmeter/setup/TestData_SCIM2_Add_User.jmx
- pre-provisioned/run-performance-tests.sh
- single-node/run-performance-tests.sh
- two-node-cluster/run-performance-tests.sh
> Parameterise tenant count sp count and user count
> Parameterise tenant count sp count and user count

- common/is/clean-database-mssql.sql
- common/is/truncate_non_empty_table.sql
> SQL Scripts for truncating tables in Azure SQL 
> Tested with Microsoft SQL Azure (RTM) - 12.0.2000.8
> Add SQL scripts for Azure SQL

- common/jmeter/setup/TestData_Add_Tenant_OAuth_Apps.jmx
> Fix audience and token binding issue
> Fix audience and token binding issue

- pre-provisioned/start-performance.sh
- single-node/start-performance.sh
- two-node-cluster/start-performance.sh
> Add default AWS outcome as json
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …
> Add default AWS outcome as json

- single-node/setup/resources/createDB.sql
- two-node-cluster/setup/resources/createDB.sql
> Add consent tables to Identity DB
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Add consent tables to Identity DB

- common/jmeter/saml/SAML2_SSO_Redirect_Binding.jmx
- single-node/setup/resources/deployment.toml
- two-node-cluster/setup/resources/deployment.toml
- Improve saml test case to submit credentials to samlsso endpoint (In the authenticationendpoint submit to this endpoint)
- Enable consent by default
- Add rewriteBatchedStatements=true
> Improve performance test scripts and enable consent by default

- common/jmeter/perf-test-is.sh
- common/jmeter/perf-test-pre-provisioned.sh
- pre-provisioned/run-performance-tests.sh
- pre-provisioned/start-performance.sh
- single-node/run-performance-tests.sh
- single-node/start-performance.sh
- two-node-cluster/run-performance-tests.sh
- two-node-cluster/start-performance.sh
* Add the functionality that allows to specify a "Run-Mode" (FULL/QUICK) as a parameter, so that only the required set of scenarios could be executed during the perf-tests.
> Perf test modes

- common/jmeter/oauth/OAuth_Client_Credentials_Grant.jmx
- common/jmeter/oauth/OAuth_Jwt_Grant.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oidc/OIDC_Password_Grant.jmx
- common/jmeter/perf-test-is.sh
- common/jmeter/perf-test-pre-provisioned.sh
- common/jmeter/saml/SAML2_SSO_Redirect_Binding.jmx
- single-node/start-performance.sh
- two-node-cluster/start-performance.sh
> Incorporated burst traffic into our performance test plan to showcase how the system handles sudden increases in traffic.
> Test the performance when sudden traffic increases happen.
- Onboarded burst traffic flow to the selected test scripts. Burst of 3000 concurrent requests.
- SAML2 SSO Redirect Binding
- OIDC Auth Code Grant Redirect With Consent
- Client Credentials Grant Type
- OIDC Password Grant Type
- JWT Bearer Grant Flow
- Support command line option also to enable the burst traffic flow through the Jenkins job.
> * https://github.com/wso2/product-is/issues/15460
Mail: Presenting our performance results in an optimal way to do capacity planning for our customers
> Incorporated Burst Traffic into the Performance Test Plan

- common/jmeter/perf-test-is.sh
- common/summary/summary-modifier.py
- single-node/start-performance.sh
- two-node-cluster/start-performance.sh
- Improve Summary CSV Generation Script to get Critical Request 95% Response Time
- [Selected Critical Requests for each Scenario](https://docs.google.com/spreadsheets/d/1LjCujQornGN5EZOrkMvBnrD2zHvArPHiQs5Cim9ZcKo/edit?usp=sharing)
- Parameterized the concurrency handling through the Jenkins Job
- Generate summary csv with the 95th percentile response time of critical path request
- Easily trigger a Jenkins job by providing required concurrency levels
- Improve summary csv by pre-configuring the critical request and test scenario in a Python dictionary.
- Parametrized the concurrency levels by passing it as a command line option.
> * https://github.com/wso2/product-is/issues/15460
> [wso2is-6.1.0-rc1](https://github.com/wso2/product-is/releases/download/v6.1.0-rc1/wso2is-6.1.0-rc1.zip) …
> Improve Summary CSV Generation Script to get Critical Request 95% Response Time

- README.md
- common/performance_analysis/README.md
- common/performance_analysis/performance_plots.py
The purpose of this pull request is to add a performance analysis script, `performance_plots.py`, and update the README.md file. This addition aims to provide a convenient way to generate performance plots based on CSV data files for different deployment types and scenarios. The README.md file is updated to provide instructions on how to use the script and customize the settings.
> Selected deployment types
```sh
deployment_types = {
'Single Node 4 Core': 'single_node_4_core.csv',
'Two Node 2 Core': 'two_node_2_core.csv',
'Two Node 4 Core': 'two_node_4_core.csv',
'Three Node 4 Core': 'three_node_4_core.csv',
'Four Node 4 Core': 'four_node_4_core.csv',
}
```
_Refer_
Mail: Presenting our performance results in an optimal way to do capacity planning for our customers 
1. Provide a script to …
> Add script to Generate performance graphs and update ReadMe

- common/performance_analysis/README.md
- common/performance_analysis/performance_plots.py
- common/performance_analysis/requirements.txt
1. Pre-define the colours for each line in the graph based on the deployment type.
```shell
deployment_types = {
'Single Node 4 Core': {
'csv_file': 'single_node_4_core.csv',
'color': 'blue'
},
'Two Node 2 Core': {
'csv_file': 'two_node_2_core.csv',
'color': 'black'
},
'Two Node 4 Core': {
'csv_file': 'two_node_4_core.csv',
'color': 'orange'
},
'Three Node 4 Core': {
'csv_file': 'three_node_4_core.csv',
'color': 'pink'
},
'Four Node 4 Core': {
'csv_file': 'four_node_4_core.csv',
'color': 'purple'
}
}
limits = {
'upper': {
'value': 2000,
'color': 'red',
'label': 'Upper Limit: 2000 ms'
},
'lower': {
'value': 500,
'color': 'green',
'label': 'Lower Limit: 500 ms'
}
}
```
2. Provide a requirement.txt file for installing the prerequisite for running the `performance_plots.py`.
- pandas
- …
> Improvement on performance analysis graphs

- pre-provisioned/bastion-cft.yml
- single-node/setup/resources/deployment.toml
- single-node/single-node.yaml
- single-node/start-performance.sh
- two-node-cluster/2-node-cluster.yml
- two-node-cluster/setup/resources/deployment.toml
- two-node-cluster/start-performance.sh
> To run the performance test with older mode
> * https://github.com/wso2-enterprise/iam-engineering/issues/640
> * https://github.com/wso2/product-is/issues/15460
> * https://github.com/wso2/product-is/issues/16517
> Added legacy code base

- common/is/restart-is.sh
- single-node/single-node.yaml
- two-node-cluster/2-node-cluster.yml
> $subject
> * https://github.com/wso2/product-is/issues/16517
> Updated mysql version for IS performance testing

- common/jmeter/oauth/Token_Exchange_Grant.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes_And_Groups.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes_Groups_And_Roles.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes_And_Groups.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes_Groups_And_Roles.jmx
- common/jmeter/oidc/OIDC_Password_Grant.jmx
- common/jmeter/oidc/OIDC_Password_Grant_Retrieve_User_Attributes.jmx
- common/jmeter/oidc/OIDC_Password_Grant_Retrieve_User_Attributes_And_Groups.jmx
- common/jmeter/oidc/OIDC_Password_Grant_Retrieve_User_Attributes_Groups_And_Roles.jmx
- common/jmeter/saml/SAML2_SSO_Redirect_Binding.jmx
- common/jmeter/setup/TestData_Add_Super_Tenant_Users.jmx
- common/jmeter/setup/TestData_Add_Tenant_Users.jmx
- common/jmeter/setup/TestData_Add_Tenants_And_Tenant_Users.jmx
- common/jmeter/setup/TestData_Add_images.jmx
- common/jmeter/setup/TestData_Get_OAuth_Jwt_Token.jmx
- common/jmeter/setup/TestData_SCIM2_Add_Tenant_Users.jmx
- common/jmeter/setup/TestData_SCIM2_Add_User.jmx
- common/summary/summary-modifier.py
> Add improvements to performance-is

- common/summary/summary-modifier.py
> Fixed summary-modifier file issue

- four-node-cluster/4-node-cluster.yml
- four-node-cluster/setup/resources/deployment.toml
- single-node/setup/resources/deployment.toml
- single-node/single-node.yaml
- three-node-cluster/3-node-cluster.yml
- three-node-cluster/setup/resources/deployment.toml
- two-node-cluster/2-node-cluster.yml
- two-node-cluster/setup/resources/deployment.toml
> Changes added to keystore file extension.
> Add new allowed instance type for 8 core node.
> Add keystore ext changes

- common/jmeter/oauth/OAuth_Client_Credentials_Grant.jmx
- common/jmeter/oauth/Token_Exchange_Grant.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes_And_Groups.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes_Groups_And_Roles.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes_And_Groups.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes_Groups_And_Roles.jmx
- common/jmeter/oidc/OIDC_Password_Grant.jmx
- common/jmeter/oidc/OIDC_Password_Grant_Retrieve_User_Attributes.jmx
- common/jmeter/oidc/OIDC_Password_Grant_Retrieve_User_Attributes_And_Groups.jmx
- common/jmeter/oidc/OIDC_Password_Grant_Retrieve_User_Attributes_Groups_And_Roles.jmx
- common/jmeter/saml/SAML2_SSO_Redirect_Binding.jmx
> Improved the active-passive support logic

- four-node-cluster/setup/resources/deployment.toml
- single-node/setup/resources/deployment.toml
- three-node-cluster/setup/resources/deployment.toml
- two-node-cluster/setup/resources/deployment.toml
> Add JKS keystore configs to deployment toml

- common/jmeter/oauth/OAuth_Client_Credentials_Grant.jmx
- common/jmeter/oauth/Token_Exchange_Grant.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes_And_Groups.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes_Groups_And_Roles.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes_And_Groups.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes_Groups_And_Roles.jmx
- common/jmeter/oidc/OIDC_Password_Grant.jmx
- common/jmeter/oidc/OIDC_Password_Grant_Retrieve_User_Attributes.jmx
- common/jmeter/oidc/OIDC_Password_Grant_Retrieve_User_Attributes_And_Groups.jmx
- common/jmeter/oidc/OIDC_Password_Grant_Retrieve_User_Attributes_Groups_And_Roles.jmx
- common/jmeter/saml/SAML2_SSO_Redirect_Binding.jmx
- common/summary/summary-modifier.py
> This change will improve the readability of `summary-original.csv `results sheet.
Related issues:
- https://github.com/wso2/product-is/issues/18936
> Add numbers to API Calls

- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes_And_Groups.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes_Groups_And_Roles.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes_And_Groups.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes_Groups_And_Roles.jmx
> Change burst key word place to avoid test data script issues.
> Change burst key word place

- benchmarks/README.md
> This PR will change the order of `existing version table's content` in reverse chronological order.
Addresses https://github.com/wso2/performance-is/pull/162#issuecomment-1999032089
> Change table content in reverse chronological order

- common/deployment/test_scenarios.sh
> Fix names of tests

- four-node-cluster/setup/resources/deployment.toml
- single-node/setup/resources/deployment.toml
- three-node-cluster/setup/resources/deployment.toml
- two-node-cluster/setup/resources/deployment.toml
> Added missing properties config

- common/jmeter/oidc/B2B_OIDC_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/setup/TestData_Add_Sub_Orgs.jmx
- Fix the logic to distribute the load when creating sub organization to reduce the test run time.
- Fix the logic to distribute load to nodes evenly during the perf test.
> B2b script fixes

- common/deployment/test_scenarios.sh
- common/summary/summary-modifier.py
* Make changes to return the sum of set of critical requests
* Fix display name and key name in one test scenario
> Fix the summary-modifier.py script

- four-node-cluster/4-node-cluster.yml
- single-node/single-node.yaml
- three-node-cluster/3-node-cluster.yml
- two-node-cluster/2-node-cluster.yml
> Increase the provisioned IOPS to remove IOPs bottleneck in database

- common/jmeter/perf-test-is.sh
Add new concurrency modes
* 50
* 1000-3000
Related to https://github.com/wso2/product-is/issues/21556
> Add new concurrency modes

- common/deployment/setup/update-is-conf.sh
- common/is/restart-is.sh
- common/jmeter/perf-test-is.sh
- four-node-cluster/setup/resources/deployment.toml
- four-node-cluster/start-performance.sh
- three-node-cluster/setup/resources/deployment.toml
- two-node-cluster/setup/resources/deployment.toml
Add following changes
- Increase default heap size to 4GB
- Decrease sleep for FD limit
- Update DB pool options
Related issue https://github.com/wso2/product-is/issues/21513
> Optimize performance for higher concurrencies

- common/jmeter/perf-test-is.sh
- four-node-cluster/start-performance.sh
- single-node/start-performance.sh
- three-node-cluster/start-performance.sh
- two-node-cluster/start-performance.sh
Fix estimate script not getting the parameters correctly.
> Fix estimate script

- common/jmeter/setup/TestData_Add_B2B_OAuth_Apps.jmx
- common/jmeter/setup/TestData_Add_Device_Flow_OAuth_Apps.jmx
- common/jmeter/setup/TestData_Add_OAuth_Apps.jmx
- common/jmeter/setup/TestData_Add_Pasive_STS_Apps.jmx
- common/jmeter/setup/TestData_Add_SAML_Apps.jmx
Related issue https://github.com/wso2/product-is/issues/21519
> Add application version to SOAP API

- common/deployment/setup/setup-is.sh
- common/deployment/setup/update-is-conf.sh
- common/start-performance.sh
- four-node-cluster/setup/resources/deployment.toml
- single-node/setup/resources/deployment.toml
- three-node-cluster/setup/resources/deployment.toml
- two-node-cluster/setup/resources/deployment.toml
This pull request introduces a new feature to handle case insensitivity in the user store configuration. The changes span multiple scripts and configuration files to incorporate this new functionality.
* [`common/deployment/setup/setup-is.sh`](diffhunk://#diff-d07af87bdced34b58cd18c8ca73a55c592acf6d0cedc655ffb719cf7e7b8464eR37-R41): Added a new option `-c` for case insensitivity and updated the `setup_is_node_command` to include this parameter. [[1]](diffhunk://#diff-d07af87bdced34b58cd18c8ca73a55c592acf6d0cedc655ffb719cf7e7b8464eR37-R41) [[2]](diffhunk://#diff-d07af87bdced34b58cd18c8ca73a55c592acf6d0cedc655ffb719cf7e7b8464eR73-R75) [[3]](diffhunk://#diff-d07af87bdced34b58cd18c8ca73a55c592acf6d0cedc655ffb719cf7e7b8464eL129-R142)
* …
> Add case-insensitive mode

- common/deployment/setup/setup-bastion.sh
- common/deployment/setup/setup-nginx.sh
- common/start-performance.sh
- single-node/bin.xml
- single-node/run-performance-tests.sh
- single-node/setup/README.md
- single-node/setup/resources/deployment.toml
- single-node/setup/resources/is.conf
- single-node/single-node.yaml
> Add nginx to single node deployment

- common/jmeter/oidc/B2B_OIDC_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes_And_Groups.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithConsent_Retrieve_User_Attributes_Groups_And_Roles.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes_And_Groups.jmx
- common/jmeter/oidc/OIDC_AuthCode_Redirect_WithoutConsent_Retrieve_User_Attributes_Groups_And_Roles.jmx
- common/jmeter/saml/SAML2_SSO_Redirect_Binding.jmx
> Fix useDelay parameter handling in JMeter test plans

- single-node/setup/resources/is.conf
> Updated single node keep alive

- common/tools/run-long-running-tests.sh
> Update long running script for clear code script
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Update perf long running script

- common/deployment/test_scenarios.sh
> note $subject
Need to run app native authentication perf test in bi-weekly builds.
> Add app native authentication to PUBLISH mode.
